#!/bin/bash

# Whisperrr Environment Setup Script
# Interactive script to configure environment variables for multi-service communication
# when services are not running on localhost.

set -e

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Default values
DEFAULT_HOST="localhost"
DEFAULT_FRONTEND_PORT=3737
DEFAULT_BACKEND_PORT=7331
DEFAULT_PYTHON_PORT=5001

echo -e "${BLUE}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║     Whisperrr Environment Configuration Setup            ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════════════╝${NC}"
echo ""

# Function to validate IP address format (basic check)
validate_ip() {
    local ip=$1
    if [[ $ip == "localhost" ]] || [[ $ip == "127.0.0.1" ]]; then
        return 0
    fi
    # Basic IP validation (IPv4)
    if [[ $ip =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
        IFS='.' read -ra ADDR <<< "$ip"
        for i in "${ADDR[@]}"; do
            if [[ $i -gt 255 ]]; then
                return 1
            fi
        done
        return 0
    fi
    return 1
}

# Function to validate port number
validate_port() {
    local port=$1
    if [[ $port =~ ^[0-9]+$ ]] && [ "$port" -ge 1 ] && [ "$port" -le 65535 ]; then
        return 0
    fi
    return 1
}

# Prompt for host IP
echo -e "${YELLOW}Enter the host IP address or hostname:${NC}"
echo -e "  (Use 'localhost' or '127.0.0.1' for local development)"
echo -e "  (Use an IP address like '192.168.1.100' for remote deployment)"
read -p "Host [${DEFAULT_HOST}]: " HOST
HOST=${HOST:-$DEFAULT_HOST}

# Validate host
if ! validate_ip "$HOST" && [[ ! $HOST =~ ^[a-zA-Z0-9.-]+$ ]]; then
    echo -e "${YELLOW}Warning: Host format may be invalid. Continuing anyway...${NC}"
fi

# Prompt for frontend port
echo ""
echo -e "${YELLOW}Enter the frontend port:${NC}"
read -p "Frontend Port [${DEFAULT_FRONTEND_PORT}]: " FRONTEND_PORT
FRONTEND_PORT=${FRONTEND_PORT:-$DEFAULT_FRONTEND_PORT}

# Validate frontend port
if ! validate_port "$FRONTEND_PORT"; then
    echo -e "${YELLOW}Warning: Invalid port number. Using default ${DEFAULT_FRONTEND_PORT}${NC}"
    FRONTEND_PORT=$DEFAULT_FRONTEND_PORT
fi

# Prompt for backend port
echo ""
echo -e "${YELLOW}Enter the backend port:${NC}"
read -p "Backend Port [${DEFAULT_BACKEND_PORT}]: " BACKEND_PORT
BACKEND_PORT=${BACKEND_PORT:-$DEFAULT_BACKEND_PORT}

# Validate backend port
if ! validate_port "$BACKEND_PORT"; then
    echo -e "${YELLOW}Warning: Invalid port number. Using default ${DEFAULT_BACKEND_PORT}${NC}"
    BACKEND_PORT=$DEFAULT_BACKEND_PORT
fi

# Prompt for python service port
echo ""
echo -e "${YELLOW}Enter the Python service port:${NC}"
read -p "Python Service Port [${DEFAULT_PYTHON_PORT}]: " PYTHON_PORT
PYTHON_PORT=${PYTHON_PORT:-$DEFAULT_PYTHON_PORT}

# Validate python port
if ! validate_port "$PYTHON_PORT"; then
    echo -e "${YELLOW}Warning: Invalid port number. Using default ${DEFAULT_PYTHON_PORT}${NC}"
    PYTHON_PORT=$DEFAULT_PYTHON_PORT
fi

# Construct URLs
FRONTEND_URL="http://${HOST}:${FRONTEND_PORT}"
BACKEND_URL="http://${HOST}:${BACKEND_PORT}"
PYTHON_URL="http://${HOST}:${PYTHON_PORT}"
BACKEND_API_URL="${BACKEND_URL}/api"

# Set CORS origins (comma-separated for backend, space-separated for Python)
CORS_ORIGINS="${FRONTEND_URL},http://${HOST}:${FRONTEND_PORT}"
PYTHON_CORS_ORIGINS="${FRONTEND_URL},${BACKEND_URL}"

echo ""
echo -e "${GREEN}════════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}Configuration Summary:${NC}"
echo -e "${GREEN}════════════════════════════════════════════════════════════${NC}"
echo -e "Host:              ${BLUE}${HOST}${NC}"
echo -e "Frontend Port:     ${BLUE}${FRONTEND_PORT}${NC}"
echo -e "Backend Port:      ${BLUE}${BACKEND_PORT}${NC}"
echo -e "Python Port:       ${BLUE}${PYTHON_PORT}${NC}"
echo ""
echo -e "${GREEN}Environment Variables to be exported:${NC}"
echo -e "  REACT_APP_API_URL=${BLUE}${BACKEND_API_URL}${NC}"
echo -e "  WHISPERRR_SERVICE_URL=${BLUE}${PYTHON_URL}${NC}"
echo -e "  CORS_ALLOWED_ORIGINS=${BLUE}${CORS_ORIGINS}${NC}"
echo -e "  CORS_ORIGINS=${BLUE}${PYTHON_CORS_ORIGINS}${NC}"
echo ""

# Export variables
export REACT_APP_API_URL="${BACKEND_API_URL}"
export WHISPERRR_SERVICE_URL="${PYTHON_URL}"
export CORS_ALLOWED_ORIGINS="${CORS_ORIGINS}"
export CORS_ORIGINS="${PYTHON_CORS_ORIGINS}"

echo -e "${GREEN}✓ Environment variables exported to current shell session${NC}"
echo ""

# Ask if user wants to save to file
read -p "Save these variables to a file for reuse? (y/n) [n]: " SAVE_TO_FILE
SAVE_TO_FILE=${SAVE_TO_FILE:-n}

if [[ $SAVE_TO_FILE =~ ^[Yy]$ ]]; then
    EXPORT_FILE=".env-export.sh"
    cat > "$EXPORT_FILE" << EOF
#!/bin/bash
# Whisperrr Environment Variables
# Generated by setup-env.sh on $(date)
# Source this file to set environment variables: source .env-export.sh

export REACT_APP_API_URL="${BACKEND_API_URL}"
export WHISPERRR_SERVICE_URL="${PYTHON_URL}"
export CORS_ALLOWED_ORIGINS="${CORS_ORIGINS}"
export CORS_ORIGINS="${PYTHON_CORS_ORIGINS}"

echo "Environment variables loaded from ${EXPORT_FILE}"
echo "  REACT_APP_API_URL=${BACKEND_API_URL}"
echo "  WHISPERRR_SERVICE_URL=${PYTHON_URL}"
echo "  CORS_ALLOWED_ORIGINS=${CORS_ORIGINS}"
echo "  CORS_ORIGINS=${PYTHON_CORS_ORIGINS}"
EOF
    chmod +x "$EXPORT_FILE"
    echo -e "${GREEN}✓ Variables saved to ${EXPORT_FILE}${NC}"
    echo -e "${YELLOW}  To use later, run: source ${EXPORT_FILE}${NC}"
    echo ""
fi

echo -e "${GREEN}════════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}Setup Complete!${NC}"
echo ""
echo -e "${YELLOW}Next Steps:${NC}"
echo "  1. Start the Python service: cd python-service && uvicorn app.main:app --host 0.0.0.0 --port ${PYTHON_PORT}"
echo "  2. Start the Backend service: cd backend && ./mvnw spring-boot:run"
echo "  3. Start the Frontend service: cd frontend && npm start"
echo ""
echo -e "${YELLOW}Note:${NC} These environment variables are only active in this shell session."
echo -e "      If you open a new terminal, run this script again or source the export file."
echo ""
